### ISSUE TITLE
Example on biasCorrection documentation does not work

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/downscaleR#16]
I'm using the last version of downscaleR. 
I was trying to use the bias correction capabilities on my data but I got an error message. Then I tried with the example on biasCorrection documentation and...
```
> data(VALUE_Igueldo_tp)
> data(NCEP_Iberia_tp)
> y <- VALUE_Igueldo_tp
> x <- NCEP_Iberia_tp

> eqm1 <- biasCorrection(y = y, x = x, newdata = x, method = "eqm", extrapolation = "none", window = NULL)
Error in biasCorrection(y = y, x = x, newdata = x, method = "eqm", extrapolation = "none",  : 
  y and x do not have the same time series length
```

**Comment by miturbide** [comment]
Hi Matteo
There was a bug in biasCorrection and redim, the corrected functions are now in the devel branch.

**Comment by solhailu** [comment]
Dear all ,

I am new to this package (downscaleR) and I found it very helpful. I am interested in Biascorrection and I have station and model output data(simulated and projected). I would like to start with one station and applied "biasCorrection(x, y, new, method = "eqm", theta = 0.95, window = NULL)", but this is not working. "Error in grepl(xx$Variable$varName, c("pr", "tp", "precipitation", "precip")) : 
  invalid 'pattern' argument". I need your help!!!
Thanks a lot!!!
Solomon
