### ISSUE TITLE
Biascorrection using simple station and model output data (time_series)

### ISSUE THREAD

**Issue by solhailu** [SantanderMetGroup/downscaleR#27]
Dear all ,

I am new to this package (downscaleR) and I found it very helpful. I am interested in Biascorrection and I have station and model output data(simulated and projected). I would like to start with one station and applied "biasCorrection(x, y, new, method = "eqm", theta = 0.95, window = NULL)", but this is not working. "Error in grepl(xx$Variable$varName, c("pr", "tp", "precipitation", "precip")) :
invalid 'pattern' argument". I need your help!!!
Thanks a lot!!!
Solomon

**Comment by miturbide** [comment]
Dear Solomon,

biasCorrection function needs to know if the data to be corrected is precipitation data or not. Until now, this information was provided by the variable name in the observations (y$Variable$varName), being one of those appearing in the Error:   "pr", "tp", "precipitation" or "precip".

There is an update of biasCorrection that will be merged to a new release of the package soon, where `precipitation = TRUE` (or FALSE) is specified as an argument in the function.

To solve this problem with your actual version of downscaleR, you could specify the varName of your object:

x$Variable$varName <- "pr"

**Comment by afzalreading** [comment]
Dear Solomon, 
Did that help, because I also received similar error message....
