### ISSUE TITLE
Error when interpolating field 

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/downscaleR#28]
I was trying to interpolate the variables `obs_m` (available [here](https://www.dropbox.com/s/7vjfacaeh4jzdnr/ERA.example.Rdata?dl=0)) with the following line:

```
> obs_m = interpGrid(obs_m, new.coordinates = getGrid(fcst_m), method = 'bilinear')
[2016-07-21 11:03:33] Performing bilinear interpolation... may take a while
Error in interp.old(x, y, z, xo = xo, yo = yo, ncp = 0, extrap = extrap,  : 
  duplicate data points: need to set 'duplicate = ..' 
```

The target grid is here:

```
> dput(getGrid(fcst_m))
structure(list(x = c(-178.875, 180), y = c(-39.8128523737712, 
70.0926903516245)), .Names = c("x", "y"), projection = "LatLonProjection", resX = 1.121484375, resY = 1.12148512985098)
```

the grid data seems ok to me, is this a bug?

**Comment by matteodefelice** [comment]
I've found the error. Loading a NetCDF with longitude 0-360 specifying `lonLim=c(-180,180)` with `LoadGridData` leads to a grid object with a duplicate element: there are two longitudes equals to 180 and the `Data` field has two identical "columns". To fix this I have to use `lonLim = c(-179, 180)`. Can you fix this?

**Comment by matteodefelice** [comment]
Any comment on this?

**Comment by jbedia** [comment]
I have come across this issue in some previous occasions... What about setting lonLim to NULL? Still the same problem?
thanks
