### ISSUE TITLE
The output of biasCorrection cannot be plotted with plotclimatology

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/downscaleR#30]
After performed a biasCorrection of a seasonal forecast with `biasCorrection` I've tried to plot the output by using `plotMeanGrid` or `plotClimatology` but...

```
> plotClimatology(climatology(cal), 'coastline')
Error in aperm.default(obj$Data, perm) : 
  'perm' is of wrong length 4 (!= 7)
```

**Comment by miturbide** [comment]
Thanks Matteo. After fixing the biasCorrection function, the attribute "dimensions" of the bias corrected grid is now returned, so the plotClimatology function (and others that rely on this attribute) can be applied.

**Comment by jbedia** [comment]
plotClimatology is now deprecated. Replaced by visualizeR::spatialPlot
