### ISSUE TITLE
Missing dimensions in bias corrected grid data

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/downscaleR#33]
I don't know if it's related with the issue #31 
However,
after bias correcting a gridded field with:

```
cal <- biasCorrection(y = obs,
                      x = fcst,
                      newdata = fcst,
                     cross.val = 'kfold',
                     folds = as.list(1984:2007),
                      method = "eqm")
```

(btw, please add an example on the use of k-fold CV because I had to read the source code to understand what I had to put into `folds`)
If I check the dimensions of `cal`:

```
> str(cal$Data)
 num [1:2208, 1:35, 1:50] 293 293 294 294 294 ...
```

As you can see, the dimensions attribute is missing, creating problems with other functions like `aggregateGrid`, in fact:

```
> c_mon = aggregateGrid(cal, aggr.m = list(FUN = mean))
[2016-09-20 09:38:46] Performing monthly aggregation...
Error in apply(grid$Data, MARGIN = mar, FUN = function(x) { : 
  dims [product 1] do not match the length of object [3864000]
```

If I add manually the dimensions, everything works.

**Comment by miturbide** [comment]
Hi Matteo,

I have just commented this in issue #30.

We will add an example with k-fold.

Thanks!

**Comment by brajrajladdha21** [comment]
Unable to biascorrect 1D data
