### ISSUE TITLE
A minor bug in gpqm function?

### ISSUE THREAD

**Issue by RatyO** [SantanderMetGroup/downscaleR#35]
Dear all,

I was checking the R source code for gpqm function in biasCorrection.R and found an oddity from line 712. The line states that if auxF2=1, the adjusted precipitation values are obtained using max(o[indpareto]). If I have understood correctly, wrong indpareto values are now used since the same variable contains indices for p at this point, whereas indices calculated for o shoud be used.

Cheers,

Olle Räty

**Comment by miturbide** [comment]
Dear Olle Räty,

Thank you very much for reporting.
We have fixed this bug by renaming the indices corresponding to p values.
The corrected function is now in the devel branch.

Cheers,

Maialen
