### ISSUE TITLE
datainventory

### ISSUE THREAD

**Issue by niteshshrestha** [SantanderMetGroup/downscaleR#36]
Hi there,

I find the tool very useful as it serves my purpose of bias correction. As I downloaded V2.0, and started to work on it as per Wiki, it seems like some of the functions as per wiki has not been updated in latest version like dataInventory, loadstationdata, etc. I further realized that it requires loadeR, but everytime installing these packages say that the package is not available for R version 3.3.2, while in description file it works for R > 3.0.0. Could you please suggest on this?

I am very new to this tool, so look forward to your valuable guidance. Moreover, pdf version of wiki with step by step guide would be much appreciated by new users like me. Thanking you, Nitesh

**Comment by jbedia** [comment]
Hi Nithesh.
Thanks for your ticket. Some examples in the wiki are a bit outdated, sorry for that. The wiki is planned to be updated in the coming weeks/months with new case studies and updated examples. Regarding package version, I suspect that some dependency (not downscaleR) is requiring a higher version of R. I strongly suggest to update R to its current stable version.
