### ISSUE TITLE
Further explaination of the window argument in biasCorrection

### ISSUE THREAD

**Issue by gcurci** [SantanderMetGroup/downscaleR#37]
I am having some difficulties in deeply understanding the machinery behind the optional "window" argument in the biasCorrection function.

A moving window is specified with two numbers: the window length and the window step. According to the wiki, the purpose is to obtain correction factors for each day of the year (doy). The window lenght is thus the number of days around each doy that is used to estimate the bias correction. The role of the window step is less clear: from my understanding if the step is 1, then the bias correction is done actually for each doy, it the step is n > 1, then the bias correction is done every n doy's. In practice, this will somewhat contradict the wiki page, since the correction will not be done for each doy, but actually at groups of doy's each consisting of n (step) days.

Is that correct? Thanks!

**Comment by miturbide** [comment]
You are right, we need to update the wiki at this respect, thanks for reporting!
The step refers to the group of days that are being corrected in each window. 
The description of the parameter provided in the help documentation of the function is the following:
window: vector of length = 2 specifying the time window width used to calibrate and the target days (days that are being corrected). The window is centered on the target day/s.

**Comment by gcurci** [comment]
Ok, thanks for the clarification. If I understand well, the most "refined" method should be with a step of 1 and a window lenght tuned for the specific application. Basically, a step > 1 is useful to save computational time, right?

**Comment by miturbide** [comment]
that is right
