### ISSUE TITLE
How to get netcdf file for output of bias correction

### ISSUE THREAD

**Issue by anubhavchoudhary** [SantanderMetGroup/downscaleR#38]
Hello all,
I am new to using downscaleR for bias correction. 
I am able to apply different bias correction methods on my gridded RCM data using gridded observational data for e.g. using 'eqm' method as under,
cal <- biasCorrection (y = y, x = x, newdata = x, precipitation = TRUE, method = "eqm")
it is working fine and I am able to visualize the bias corrected results from "cal". 
**But I also want to get a netcdf file output of bias corrected data.** How is it possible? Please give suggestions.

Regards
Anubhav

**Comment by jbedia** [comment]
Hi Anubhav,
Thanks for your ticket.
To export to netCDF please have a look to [loadeR.2nc](https://github.com/SantanderMetGroup/loadeR.2nc)

**Comment by anubhavchoudhary** [comment]
Thanks a lot Joaquin. loadeR.2nc is working. I am now able export the results to netcdf file.
Many thanks to the team at SantanderMetGroup who are continuously developing this package downscaleR.
