### ISSUE TITLE
Error while using isimip bias correction

### ISSUE THREAD

**Issue by AZIZRIZWAN** [SantanderMetGroup/downscaleR#39]
Hello Everyone,
I'm very new with all this stuff so i really need help.
I'm trying to use isimip bias correction. i was able to load grid and station data. 
First i tried interpolation by following the codes/example given at 
https://github.com/SantanderMetGroup/downscaleR/blob/devel/R/isimip.R
so when i run this code,
obs <- interpGrid(obs, new.coordinates = getGrid(prd), method = "nearest")

The following error came,

NOTE: argument 'bilin.method' ignored for nearest neighbour interpolation
Error in obj$xyCoords$x : $ operator is invalid for atomic vectors

Then i tried to run code for isimip bias correction without interpolation but it also didn't work and gave following message.

simBC <- isimip (obs, prd, sim, threshold = 1)
Error in aperm.default(auxObs, match(attr(pred$Data, "dimensions")[setdiff(1:length(dimPred),  : 
  value out of range in 'perm'
In addition: Warning message:
In if ((any(grepl(obs$Variable$varName, c("tas", "mean temperature",  :
  the condition has length > 1 and only the first element will be used

I would really appreciate if someone help me out.
Thank you!
Rizwan

**Comment by miturbide** [comment]
Hello AZIZRIZWAN,

It seems that obs and/or prd objects do not have the correct structure. 
Would you mind to post the result of applying 
> str(obs) 
> str(prd)
?
Otherwise you could also provide some data so we can analyze in detail the cause of the error.

You could also try installing the new release of transformeR.
