### ISSUE TITLE
Error in if (Pth <= threshold) { : missing value where TRUE/FALSE needed_

### ISSUE THREAD

**Issue by anubhavchoudhary** [SantanderMetGroup/downscaleR#40]
Dear all,
I am using transformeR version 1.1.1 (2017-09-04)  and downscaleR version 2.0.4 (2017-09-04).
I am getting the following error while performing bias correction on my files (y= observation data, x=model data) for training period

_cal <- biasCorrection (y, x, x, precipitation = TRUE, method = "eqm")
[2017-09-06 01:17:28] Bias-correcting member 1 out of 1...
Error in if (Pth <= threshold) { : missing value where TRUE/FALSE needed_

Although, I have interpolated both the files on a common grid and other attributes like missing value, are also kept same. I am not able to understand this error. Please help.

Thanks
Anubhav

**Comment by anubhavchoudhary** [comment]
With reference to the above post, I would like to add that when I put observation data 'y' in place of model data 'x' in this way-

_cal <- biasCorrection (x, y, y, precipitation = TRUE, method = "eqm")_

then no error comes out and bias correction is completed. 
I tried to go through the biasCorrection.R code to understand error in Pth <= threshold but it is not clear  to me if the threshold precipitation to negate drizzle needs to be set here or something else.

**Comment by miturbide** [comment]
Dear @anubhavchoudhary ,

Please provide a reproducible example so we can help you.
