### ISSUE TITLE
How to apply bias correction to RCP simulation by correcting historical simulation 

### ISSUE THREAD

**Issue by arulalant** [SantanderMetGroup/downscaleR#41]
Hai All,
I have doubt in biascorrection of future (say RCP) simulation of model by using historical simulation of model and observation.
Let me first correct the historical simulation bias by passing y as observation and x as historical simulation by using the below line.
cal.t <- biasCorrection (y = y.t, x = x.t, newdata = x.t, method = "eqm")

**Now how should I apply the same bias correction to the future simulation (say RCP) outputs from the bias correction results of historical outputs ?**

Thanks in advance.
Arulalan.T

**Comment by anubhavchoudhary** [comment]
you have to pass your future simulation data as newdata. y and x will remain as it is

**Comment by arulalant** [comment]
So if I pass newdata as historical, then historical will be bias corrected and if I pass newdata as RCP simulation then that will be bias corrected based on y and x. Thanks for clarification @anubhavchoudhary
