### ISSUE TITLE
error in bias correction when using a masked file as observation data

### ISSUE THREAD

**Issue by anubhavchoudhary** [SantanderMetGroup/downscaleR#42]
@jbedia 

I am applying eqm method to bias correct my model data (x). my observation data (y) is masked to contain India and so is the model data (x). both are masked on a common boundary and have exactly same number of missing and non-missing values and the total number of grid points. but still I am getting this error on applying bias correction command

_cal <- biasCorrection (y, x, x, precipitation = TRUE, method = "eqm")
[2017-09-08 21:33:07] Bias-correcting member 1 out of 1...
Error in if (Pth <= threshold) { : missing value where TRUE/FALSE needed_

Please help. I am not able to understand this error. This problem is only with quantile mapping methods and does not occur when I use other methods like- multiplicative scaling or ptr. also when I replace the missing value in my observation file with some random meaningful constant, then the bias correction process is completed without any error but this is not a solution.
any help will be highly appreciated

**Comment by miturbide** [comment]
Dear @anubhavchoudhary,

We have done several tests with missing values in the observation data and the function performed well. Please provide a reproducible example so we can help you.
