### ISSUE TITLE
possible bug in implementing "loci" in biascorrect.R

### ISSUE THREAD

**Issue by jvra** [SantanderMetGroup/downscaleR#43]
Hi
On going through the R code for implementing loci, i think  "s" is wrongly used instead of "p" at the following places:

            gcmr <- rev(sort(s))     (SHOULD be p]
            mgcm <- mean(s[which(s > Pgcm)], na.rm = TRUE)  [SHOULD be p]

**Comment by miturbide** [comment]
Hi @jvra,
Thank you very much for reporting.
@szabotakacsb, could you please check this out?

**Comment by szabotakacsb** [comment]
Hi jvra and miturbide,
I have already corrected this issue some months ago and I made a pull request to add the corrected loci. Can you see that? In the corrected version the code is:
```
gcmr <- rev(sort(p))
gcmrs <- rev(sort(s))
Pgcm <- gcmr[l + 1]
Pgcms <- gcmrs[l + 1]
 mobs <- mean(o[which(o > threshold)], na.rm = TRUE)
 mgcm <- mean(p[which(p > Pgcm)], na.rm = TRUE)
 scaling <- (mobs - threshold) / (mgcm - Pgcm)
 GCM <- (scaling*(s - Pgcms)) + threshold
```
Please let mi know if the corrected one does not exist in biasCorrection.R

**Comment by miturbide** [comment]
Thanks @szabotakacsb.
I have not seen the pull request, but I have changed the function and is now updated in the devel branch.

**Comment by szabotakacsb** [comment]
Hi, Meantime I checked the cross-validation of LOCIbias correction in Matlab and I foud a mistake in the verion in downscaleR. I tried to pull request it but I could not. Could you change it by:
```
loci <- function(o, p, s, precip, pr.threshold){
      if (precip == FALSE) { 
            stop("method loci is only applied to precipitation data")
      } else {
            threshold <- pr.threshold
            l <- length(which(o > threshold))
            gcmr <- rev(sort(p))
            Pgcm <- gcmr[l + 1]
            # local scaling factor
            mobs <- mean(o[which(o > threshold)], na.rm = TRUE)
            mgcm <- mean(p[which(p > Pgcm)], na.rm = TRUE)
            scaling <- (mobs - threshold) / (mgcm - Pgcm)
            GCM <- (scaling*(s - Pgcm)) + threshold
            GCM[which(GCM < threshold)] <- 0
      }
      return(GCM)
```
}
Just have to comment out `gcmrs` and `Pgcms`. Thank you for your help!

**Comment by jvra** [comment]
Thanks for fixing the bug.
