### ISSUE TITLE
Bias Correction for Vector data

### ISSUE THREAD

**Issue by AZIZRIZWAN** [SantanderMetGroup/downscaleR#44]
Hello, 
I have used isimip bias correction by following the procedure given in example.  But it gives the results in form of same grids for whole area defined by latlon limits. I would really appreciate if someone can guide me if this method can be used in such a way that it returns the corrected values only for station grids instead of whole area. 
For example I have 50 stations for temperature/ precipitation and I have 50 model times series data already extracted for the grids in which station falls, the bias correction should return the 50 times series.  
Thank you in advance

**Comment by whise** [comment]
I would like this also

**Comment by jbedia** [comment]
Hi, thanks for your question.
Your station data should be introduced in the [appropriate station format](https://github.com/SantanderMetGroup/loadeR/wiki/Standard-(ASCII)-format-for-station-data), and the function will take car of the appropriate interpolation and transformations needed, as well as metadata.
I hope this helps
