### ISSUE TITLE
Error when applying an analog method on a single station with the downscale.predict function

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/downscaleR#46]
I am using this package to carry out a downscaling between a gridded field and a set of stations. Everything works when:
```
data = prepareData(x = nc_data, 
                     y = stn_c4r) 
  
  model1 <- downscale.train(data, method = "analogs", n.analogs = 3)
```
but if I try:
```
newdata = prepareNewData(newdata = nc_data %>% subsetYears(years = Y),
                           data)
m1test = downscale.predict(newdata, model1)
```
I got an error:
```
Error in array(unlist(p), dim = dim(p[[1]])) : 
  'dims' cannot be of length 0
```
this is because in line 63 of `downscale.predict` you have:
```      
p <- array(unlist(p), dim = c(n, dim(p[[1]])))
```
but in this case, given that `stn_c4r` is a single station, for the analog case in `p[[1]]` there is a numeric vector, leading to a `NULL` dimensions vector. Differently, when using `GLM` there you can find a matrix and then everything is working. 
P.S. I am using the devel version of downscaleR

**Comment by jbedia** [comment]
Hi Matteo, thanks for reporting.Jorge is currently doing fast developments and some unstabilities may occur in the devel branch. @jorgebanomedina , can you please have a look to this? thanks!

**Comment by jorgebanomedina** [comment]
Hi Matteo,

Thanks for your feedback! I fixed the problem and now downscale.train and
downscale.predict works well when downscaling to a single-station with the
analogs method. You can find the updates in the devel branch.

Regards,

Jorge

2018-05-23 9:56 GMT+02:00 Joaquin Bedia <notifications@github.com>:
