### ISSUE TITLE
Help with downscale.cv

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/downscaleR#47]
Hi, following the suggestion of @jbedia I am trying to implement a leave-one-year-out cross-validation directly with `downscale.cv` instead of implementing manually the procedure.

Currently, I do something like:
```
data <- prepareData(
        x = nc_data %>% subsetYears(years = train_years),
        y = stn_c4r %>% subsetYears(years = train_years)
      )
model1 <- downscale.train(data, method = "analogs", n.analogs = 3)
...
```
and it works. Instead, I tried with:
```
m1 <- downscale.cv(x = nc_data, y = stn_c4r, 
                         method = "analogs", folds = 4)
```
And I got:
```
[1] "fold: 1 --> calculating..."
[2018-05-30 14:30:21] - Scaling ...
Error in checkSeason(grid, base) : Inconsistent seasons among input grids
```
If I change the number of folds I get the same error but in a different fold calculation...
Do you have an updated (I'm using the devel channel) example to be used here?

Thank you in advance!

**Comment by jbedia** [comment]
Hi Matteo, thanks for reporting. I leave this issue to @jorgebanomedina who is currently working with this function. Are you sure the season of predictor and predictand are consistent? (I guess so, but just in case...). btw, @jorgebanomedina, would it be possible to replace `print` by `message`? Thanks

**Comment by matteodefelice** [comment]
I am not sure to fully understand your question...they are both daily datasets, and as I said without downscale.cv everything was working fine...should I check something in particular?

**Comment by jbedia** [comment]
The error is being raised by a helper function in `transformeR` called `checkSeason`. Could you please try `checkSeason(nc_data, stn_c4r)` and report the result?

**Comment by matteodefelice** [comment]
If I type ` checkSeason(nc_data, stn_c4r)` I don't get anything, is this a good thing?

**Comment by jbedia** [comment]
Yest, it is just a checker. It ensures that `getSeason(nc_data)` and `getSeason(stn_c4r)` yield the same result. My guess is that the season is not complete in all years within your data, and that is something that the function should handle without bothering you... I think Jorge is already aware of this problem, so he can probably fix it soon.

**Comment by jbedia** [comment]
Hi Matteo, after asking @jorgebanomedina , I see the problem now. By default, `downscale.cv` won't assume a one-year out cross validation, but 4 folds randomly sampled across time (but see the `type` argument for other setups). What you want to do, can be achieved as shown in the examples section. For instance, four folds (years are just invented as example):

```R
pred <- downscale.cv(x = nc_data, y = stn_c4r, 
                     method = "analogs",
                     folds = list(c("1985","1986","1987"),
                                  c("1989","1990","1991"),
                                  c("1993","1994","1995"),
                                  c("1998","1992","1999")))
```
You can also play with functions `getYearsAsINDEX` and `sample` to randomize the year selection...

Also, @jorgebanomedina recommends updating dowscanleR yo the most recent devel version. We definitely need a version update asap. Just let us know if it is working properly. A presto

**Comment by matteodefelice** [comment]
I will try this solution asap, but is the function able to calculate the out-of-sample output, in other words with the years kept out from the cross-validation?

**Comment by matteodefelice** [comment]
Just updated to the latest devel commit. 
```
pred <- downscale.cv(x = nc_data, y = stn_c4r, 
+                      method = "analogs",
+                      folds = list(c("2011","2012","2013"),
+                                   c("2014","2015","2016"),
+                                   c("2011","2013","2017"),
+                                   c("2011","2014","2015")))
fold: 1 --> calculating...
NOTE: Variable subsetting was ignored: Input grid is not a multigrid object
Error in rep(dist.sorted[-(1:ind_zeros)][1:info$n.analogs], ncol(y)) : 
  invalid 'times' argument
```

**Comment by jorgebanomedina** [comment]
Hi Mateo,

Could you please indicate how many stations do you have in "stn_c4r", 
and more precisely if it is of class vector or not? Have you downloaded 
stn_c4r via loadStationData?

Jorge

**Comment by matteodefelice** [comment]
Sorry for the very late reply! Now everything works, I'm using the latest release and I've fixed an issue in the station data.
Just a question now? The documentation says that `downscale.cv` returns "The reconstructed downscaled temporal serie.". Then I expected to find in the `Data` field of the returned list a structure of the same size of the predictand (`y`), instead if I set the folds specifying the years  I get as output the concatenation of all the cross-validated outputs. 

For example, my station data has length 1000. If I set `folds = 10` the output length (in `$Data`) is 1000. Instead if I specify the years with 6 folds (`list(c(2011, 2012, 2013, 2014, 2015, 2016), c(2011, 
2012, 2013, 2014, 2015, 2017), ..., c(2012, 2013, 2014, 2015, 2016, 2017))`) the output length is 6000. I think this is normal, because probably in this case the function does not know how to "reconstruct" the output, but in this case I'd suggest to update the documentation.

**Comment by matteodefelice** [comment]
This means that a leave-one-year-out cross-validation is not possible?

**Comment by jorgebanomedina** [comment]
Hi @matteodefelice,

I have changed the code in downscale.cv to stop if this case happens. 
Also I have added an explanation of the latter in the section "Details" 
of downscale.cv 's help.

To perform a leave-one-out cross validation you have to arrange the 
folds like the following:

pred <- downscale.cv(x,y,type = "chronological",
                      method = "GLM", condition = "GT", threshold = 0,
                      scale.list = list(type = "standardize"),
                      folds = list(c("1985"),
                                        c("1986"),
                                        c("1987"))

)

Every member of the list represents a fold. So in this case, we our list 
"folds" has three members, such that:
folds[[1]] = "1985"; folds[[2]] = "1986"; folds[[3]] = "1987".
...or faster, folds = as.list(1985:1987)
Thus, the list represents the splitting in folds. And then depending 
automatically handles which folds are used for training and which are 
used for testing.

We are planning to make the leave-one-year-out procedure simpler for the 
user and there will be changes soon.

Regards,

Jorge

**Comment by matteodefelice** [comment]
Good! It seems to work perfectly!

**Comment by jbedia** [comment]
Excellent. We need to update `downcale.cv` to properly handle the leave-one-year-out cv. `transformeR::getYearsAsINDEX` should be used to define the year indices, in order to adequately handle incomplete annual data or year-crossing seasons (e.g. DJF datasets). @jorgebanomedina, I suggest to open an issue to address this. Cheers

**Comment by jbedia** [comment]
Hi @matteodefelice. We have updated the `downcale.cv` arguments and its documentation. It has changed a bit, so please upgrade to v3.0.1 and update your script accordingly. For leave-one-year-out, it now suffices with using the argument `sampling.strategy = "leave-one-year-out"`, so you don't need to worry about specifying a long list of years. Also, years are now given as integers (not characters as before). We hope these new changes ease the usage of the function. A presto.
