### ISSUE TITLE
Error loading "downscaleR"

### ISSUE THREAD

**Issue by dmbettin** [SantanderMetGroup/downscaleR#49]
hello @jbedia...Thank you for your great work.

I am trying to load the library "downdcaleR", but I am encountering this error:
`> library(downscaleR)`
```
Error: package or namespace load failed for ‘downscaleR’:
 object ‘bindGrid.member’ is not exported by 'namespace:transformeR'
```

Y also tried to reinstall the package, but it didn't work.

Thank you in advance.

**Comment by jbedia** [comment]
Hi @dmbettin. It was my fault, I forgot to publish an update.
It should work now. Note that `transformeR` >=1.4.3 is required (I guess you already have it, otherwise not receiving the error)
thanks for reporting!

**Comment by jbedia** [comment]
Hi again, I assume that the issue is solved, so I close this now. Cheers
