### ISSUE TITLE
fail to install this package from github

### ISSUE THREAD

**Issue by junliscut** [SantanderMetGroup/downscaleR#50]
l run the follwing code in R:
library('devtools')
install_github(c("SantanderMetGroup/downscaleR"))

but it fail to install and the error message is displayed as follows：

* installing *source* package 'downscaleR' ...** R
** byte-compile and prepare package for lazy loading
Error : object 'bindGrid.member' is not exported by 'namespace:transformeR'
ERROR: lazy loading failed for package 'downscaleR'
* removing 'C:/Users/user/Documents/R/win-library/3.5/downscaleR'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by jbedia** [comment]
Hi @junliscut. Fixed, (see my comment in issue #49). Thanks for reporting!

**Comment by junliscut** [comment]
Thank you for your great work~~

**Comment by jbedia** [comment]
Excellent, thank you, I am closing the issue now.
