### ISSUE TITLE
Can I apply the Bias Correction methods in monthly series?

### ISSUE THREAD

**Issue by Natel-Carolina** [SantanderMetGroup/downscaleR#55]
Can I apply the methods to monthly data?

I looked up in the code and the formulation of the methods. And I think it is possible, but I would like to confirm.

In case daily data is necessary, is it generated a monthly scale factor? As example, in Linear scaling, we could have one factor to each month (12 correction factors).

Can anyone help?

**Comment by miturbide** [comment]
Hello @Natel-Carolina ,
Sorry for the delayed response.
Although the functions were written with daily data in mind, they could also be applied to monthly data.
