### ISSUE TITLE
repeated variable names in multigrids

### ISSUE THREAD

**Issue by miturbide** [SantanderMetGroup/downscaleR#6]
Function ppModelSetUp for downscaling should differentiate grids with the same variable name in a multigrid (e.g. grids of different levels). Otherwise variable names in the multigrid need to be reassigned before downscaling.

**Comment by jbedia** [comment]
@miturbide, can you handle this?
thnks

**Comment by miturbide** [comment]
Minor change in makeMultiGrid: The level of a variable is pasted to the varName when creating a multigrid.
