### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by rodaguayo** [SantanderMetGroup/downscaleR#74]
I recently updated the library and I got the following error after: biasCorrection (). It appears to be independent of the downscalind method.

Time difference of 31 days
Error in arr[, , , ind, , ] <- grid[["Data"]] : 
number of items to replace is not a multiple of the length of the replacement

**Comment by miturbide** [comment]
This error was related to a deficient dates handling in the `transformeR` package.
It is solved now in transformeR 2.1.1

**Comment by rodaguayo** [comment]
Thanks!
