### ISSUE TITLE
illustrative datasets are missing from downscalleR

### ISSUE THREAD

**Issue by durutti** [SantanderMetGroup/downscaleR#78]
Hi,
I am user of downscalleR. The illustrative datasets seem to be missing in the latest version downscaleR 3.3.1 (2020-06-04) 

for instance, if i copy paste form the wiki
library(downscaleR)
data("VALUE_Iberia_tas") # illustrative datasets included in transformeR
y <- VALUE_Iberia_tas

I get the following warning and error
Warning message:

In data("VALUE_Iberia_tas") : data set ‘VALUE_Iberia_tas’ not found
> y <- VALUE_Iberia_tas 
Error: object 'VALUE_Iberia_tas' not found

**Comment by vjjan91** [comment]
Just got the same issue, any fixes yet?

**Comment by durutti** [comment]
I found out that datasets exist in a different package
devtools::install_github("SantanderMetGroup/climate4R.datasets")

Now the illustrative datasets are available

**Comment by vjjan91** [comment]
Aah, Thanks a ton!
